### ISSUE TITLE
make sure new time period vocab terms appear in the RDF exports

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#164]
Including the "same as" data.

**Comment by skleinfeldt** [comment]
Assigning to @paregorios for testing.

**Comment by paregorios** [comment]
It looks to me like, as of the last run on 12 June. the RDF export of time periods on staging are still serializing the old vocabulary. Here's the set of triples being created for a given term now:

``` 
<http://pleiades.stoa.org/vocabularies/time-periods/middle-geometric> a <http://www.w3.org/2004/02/skos/core#Concept>;
    skos:inScheme <http://pleiades.stoa.org/vocabularies/time-periods>;
    skos:prefLabel "Middle Geometric (Greek; 850-750 BC)"@en;
    skos:scopeNote "The Middle Geometric period in ancient Greece, from 850-750 before the birth of Christ. [[-850, -750]]"@en .
```

In addition to producing this from the new vocabulary, we would want to add a triple to express the value in the "same as" field:

```
<http://pleiades.stoa.org/vocabularies/time-periods/middle-geometric> a <http://www.w3.org/2004/02/skos/core#Concept>;
    skos:inScheme <http://pleiades.stoa.org/vocabularies/time-periods>;
    skos:prefLabel "Middle Geometric (Greek; 850-750 BC)"@en;
    skos:scopeNote "The Middle Geometric period in ancient Greece, from 850-750 before the birth of Christ. [[-850, -750]]"@en;
    owl:sameAs <http://n2t.net/ark:/99152/p03wskdjcqv> . 
```

If the "same as" field on the term is blank, this final triple should be suppressed in the RDF output. 

Note that we will need to add a definition at the top of the file for the "owl" prefix. Here's what we have now:

```
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
```

and here's what we want after the upgrade:

```
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix owl: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
```

Later, after initial deployment, we will circle around to add RDF expressions for the start and end year values, but given the structured nature of the W3C time ontology and the way it is used (in JSON) by the Periodo project, we'll want to consult with the latter about its expression.

**Comment by paregorios** [comment]
fyi @atomrab @rybesh

**Comment by rybesh** [comment]
> Later, after initial deployment, we will circle around to add RDF expressions for the start and end year values, but given the structured nature of the W3C time ontology and the way it is used (in JSON) by the Periodo project, we'll want to consult with the latter about its expression.

BTW, here's what it looks like in Turtle:
```turtle
<http://n2t.net/ark:/99152/p03wskdjcqv>
    time:intervalFinishedBy [
      skos:prefLabel "-750";
      time:hasDateTimeDescription [
        time:year "-0750"^^xsd:gYear
      ]
    ];
    time:intervalStartedBy [
      skos:prefLabel "-850";
      time:hasDateTimeDescription [
        time:year "-0850"^^xsd:gYear
      ]
    ];
```

**Comment by davisagli** [comment]
@paregorios this is ready for testing on staging, including drawing from the new vocabulary and including the `sameAs` triple.

**Comment by paregorios** [comment]
@davisagli is there a way we can get an out-of-cycle run of the RDF TTL export on staging?

**Comment by davisagli** [comment]
Sure, I just kicked it off...

**Comment by davisagli** [comment]
And done.

**Comment by paregorios** [comment]
@davisagli unfortunately, time-periods.ttl appears to be zero-length

**Comment by davisagli** [comment]
Okay, I don't think we remembered to pay attention to that one. We'll take a look.

**Comment by paregorios** [comment]
removing "review" label pending addressing of zero-length time-periods.ttl

**Comment by davisagli** [comment]
@cguardia what's the status of this?

**Comment by cguardia** [comment]
I fixed it on jazkarta-plone4.

**Comment by davisagli** [comment]
Now it fails with:
```
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/parts/debug-instance/bin/interpreter", line 313, in <module>
    exec _val
  File "<string>", line 1, in <module>
  File "./dump-scripts/rdf.py", line 89, in <module>
    g = g.scheme('time_periods')
  File "/srv/python27-apps/pleiades4/src/pleiades.rdf/pleiades/rdf/common.py", line 717, in scheme
    g = self.dcterms(self.context, g)
  File "/srv/python27-apps/pleiades4/src/pleiades.rdf/pleiades/rdf/common.py", line 180, in dcterms
    creators, contributors = principals(context)
  File "/srv/python27-apps/pleiades4/src/pleiades.rdf/pleiades/rdf/common.py", line 122, in principals
    creators = list(context.Creators())
AttributeError: Creators
```

**Comment by davisagli** [comment]
@paregorios we've got this working now, and I manually ran the time-periods.ttl dump so you can take a look.

**Comment by paregorios** [comment]
This looks right. Please deploy to production.

**Comment by davisagli** [comment]
> Please deploy to production.

@paregorios Meaning all of the changes related to the new implementation of the time periods vocabulary, plus the addition of the archaeological remains field?

**Comment by paregorios** [comment]
Yes, please deploy to production everything related to scrumdo stories 26
and 34. I'll mark them accordingly.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davisagli** [comment]
Okay, I will work on that.

**Comment by davisagli** [comment]
Deployed.

**Comment by paregorios** [comment]
Will add a couple on production today and verify after the next run, at which point I will close this ticket.
