### ISSUE TITLE
Pleiades KMZ dumps for last two days are busted

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#172]
pleiades-20160627.kmz and pleiades-20160628.kmz contain only the following string:

```
PK



```

**Comment by davisagli** [comment]
Traceback is
```
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/parts/debug-instance/bin/interpreter", line 313, in <module>
    exec _val
  File "<string>", line 1, in <module>
  File "./dump-scripts/kml.py", line 13, in <module>
    macros={'kml_template': main_macros, 'kml_macros': kml_macros})
  File "/srv/python27-apps/pleiades4/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 108, in __call__
    return self.pt_render(self.pt_getContext(args, kwargs))
  File "/srv/python27-apps/pleiades4/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/srv/python27-apps/pleiades4/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 240, in __call__
    interpreter()
  File "/srv/python27-apps/pleiades4/src/collective.newrelic/collective/newrelic/patches/talinterpreter.py", line 17, in monkeypatch
    newrelic_monkeypatch(self)
  File "/srv/python27-apps/pleiades4/eggs/newrelic-2.62.0.47-py2.7-linux-x86_64.egg/newrelic/api/function_trace.py", line 104, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 888, in do_useMacro
    self.interpret(macro)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 946, in do_defineSlot
    self.interpret(slot)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 821, in do_loop_tal
    self.interpret(block)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 852, in do_condition
    self.interpret(block)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 583, in do_setLocal_tal
    self.engine.setLocal(name, self.engine.evaluateValue(expr))
  File "/srv/python27-apps/pleiades4/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/srv/python27-apps/pleiades4/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py", line 217, in __call__
    return self._eval(econtext)
  File "/srv/python27-apps/pleiades4/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py", line 194, in _eval
    ob = self._subexprs[-1](econtext)
  File "/srv/python27-apps/pleiades4/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py", line 124, in _eval
    ob = self._traverser(ob, element, econtext)
  File "/srv/python27-apps/pleiades4/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py", line 34, in simpleTraverse
    next = getattr(object, name, _marker)
  File "/srv/python27-apps/pleiades4/src/pleiades.kml/pleiades/kml/browser.py", line 365, in snippet
    timespan = self.timeSpanAD
  File "/srv/python27-apps/pleiades4/src/pleiades.kml/pleiades/kml/browser.py", line 415, in timeSpanAD
    span = self.timeSpan
  File "/srv/python27-apps/pleiades4/src/pleiades.kml/pleiades/kml/browser.py", line 397, in timeSpan
    vocab = get_vocabulary('time_periods')
  File "/srv/python27-apps/pleiades4/src/pleiades.vocabularies/pleiades/vocabularies/vocabularies.py", line 39, in get_vocabulary
    registry = getUtility(IRegistry)
  File "/srv/python27-apps/pleiades4/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 169, in getUtility
    raise ComponentLookupError(interface, name)
zope.component.interfaces.ComponentLookupError: (<InterfaceClass plone.registry.interfaces.IRegistry>, '')
```

**Comment by davisagli** [comment]
The problem is that the KML dump is run in a way that doesn't set up the Plone site as the activity component site, and the new time period vocabulary requires that. Should be an easy fix fortunately.

**Comment by davisagli** [comment]
Fixed and I re-ran today's dump.

**Comment by paregorios** [comment]
Looks good! Thanks.
