### ISSUE TITLE
error while rendering pleiades.notredame.rich_meta

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#193]
Context: http://pleiades.stoa.org/places/324691/osm-location/base_view

Screenshot:

![screen shot 2016-07-25 at 10 33 17 am](https://cloud.githubusercontent.com/assets/263285/17107079/5e9a5696-5253-11e6-9476-bf0539c4be55.png)

**Comment by paregorios** [comment]
@rmhorne anything else relevant to say about this?

**Comment by rmhorne** [comment]
It seems to come and go as an error - It has currently disappeared and is no longer showing up in the edits.

**Comment by paregorios** [comment]
Possibly related traceback from instance5.log:

```
2016-07-25T11:32:54 ERROR plone.app.viewletmanager rendering of plone.htmlhead in pleiades.notredame.rich_meta fails: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/plone.app.viewletmanager-2.0.8-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/srv/python27-apps/pleiades4/eggs/plone.app.layout-2.3.13-py2.7.egg/plone/app/layout/viewlets/common.py", line 50, in render
    return self.index()
  File "/srv/python27-apps/pleiades4/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/srv/python27-apps/pleiades4/eggs/Zope2-2.13.23-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/srv/python27-apps/pleiades4/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/srv/python27-apps/pleiades4/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 240, in __call__
    interpreter()
  File "/srv/python27-apps/pleiades4/src/collective.newrelic/collective/newrelic/patches/talinterpreter.py", line 17, in monkeypatch
    newrelic_monkeypatch(self)
  File "/srv/python27-apps/pleiades4/eggs/newrelic-2.62.0.47-py2.7-linux-x86_64.egg/newrelic/api/function_trace.py", line 110, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/srv/python27-apps/pleiades4/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 620, in do_insertText_tal
    text = self.engine.evaluateText(stuff[0])
  File "/srv/python27-apps/pleiades4/eggs/Zope2-2.13.23-py2.7.egg/Products/PageTemplates/Expressions.py", line 225, in evaluateText
    text = self.evaluate(expr)
  File "/srv/python27-apps/pleiades4/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/srv/python27-apps/pleiades4/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py", line 217, in __call__
    return self._eval(econtext)
  File "/srv/python27-apps/pleiades4/eggs/Zope2-2.13.23-py2.7.egg/Products/PageTemplates/Expressions.py", line 155, in _eval
    return render(ob, econtext.vars)
  File "/srv/python27-apps/pleiades4/eggs/Zope2-2.13.23-py2.7.egg/Products/PageTemplates/Expressions.py", line 117, in render
    ob = ob()
  File "/srv/python27-apps/pleiades4/src/pleiades.notredame/pleiades/notredame/browser/viewlets.py", line 28, in formatted_title_and_content_type
    return title + ': a Pleiades '+ ct + ' resource'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)


```

**Comment by witekdev** [comment]
@paregorios fixed and deployed to production (I first deployed to staging and tested, then I didn't see you around, so I just went directly and deployed to production)

**Comment by davisagli** [comment]
This appears to be working now.
