### ISSUE TITLE
batch update: title update fails

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#200]
_Testing and reviewing [scrumdo story 12 (Batch Update of Content)](https://www.scrumdo.com/projects/story_permalink/1087991)_

Using a json file with these contents:

``` json
{
    "updates": [
        {
            "/places/70978": {
                "title": {
                    "mode": "replace",
                    "values": [
                        "Unnamed roads in the area of Vorgium"
                    ]
                }
            }
        }
    ]
}
```

I login to dev, change directories to `/srv/python27-apps/pleiades4`, sudo su to the appropriate user, and run the following command:

`bin/instance1 run scripts/batch_update.py --workflow=draft /home/thomase/updates-test.json`

I expected:
- creation of a working copy of http://pleiades.jazkarta.com/places/70978
- modification of the `title` in the working copy so that it reads "Unnamed roads in the area of Vorgium" instead of "Untitled"
- output in the command line indicating the path for the newly-created working copy
- when viewed, that working copy still in drafting state with the expected new title

What I get: no new working copy, no obvious changes, no path to the newly-created working copy. Instead, I see the following output, which is full of error notifications:

```
016-08-09 16:54:32 WARNING Init Class Products.LDAPUserFolder.LDAPUserFolder.LDAPUserFolder has a security declaration for nonexistent method 'getEncryptedPassword'
2016-08-09 16:54:32 WARNING Init Class Products.LDAPUserFolder.LDAPUserFolder.LDAPUserFolder has a security declaration for nonexistent method 'getEncryptedPassword'
2016-08-09 16:54:32 WARNING SecurityInfo Conflicting security declarations for "getPlaceTypeRaw"
2016-08-09 16:54:32 WARNING SecurityInfo Class "Place" had conflicting security declarations
2016-08-09 16:54:32 WARNING ZODB.blob (5989) Blob dir /srv/python27-apps/pleiades4/var/blobstorage/ has insecure mode setting
2016-08-09 16:54:33,124 (5989/MainThread) newrelic ERROR - Falling back to stderr logging as unable to create log file '/tmp/newrelic-python-agent.log'.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/newrelic-2.62.0.47-py2.7-linux-x86_64.egg/newrelic/common/log_file.py", line 79, in initialize_logging
    _initialize_file_logging(log_file, log_level)
  File "/srv/python27-apps/pleiades4/eggs/newrelic-2.62.0.47-py2.7-linux-x86_64.egg/newrelic/common/log_file.py", line 51, in _initialize_file_logging
    handler = logging.FileHandler(log_file)
  File "/usr/local/python/2.7.11/lib/python2.7/logging/__init__.py", line 905, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/python/2.7.11/lib/python2.7/logging/__init__.py", line 935, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/tmp/newrelic-python-agent.log'
2016-08-09 16:54:33 ERROR newrelic Falling back to stderr logging as unable to create log file '/tmp/newrelic-python-agent.log'.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/newrelic-2.62.0.47-py2.7-linux-x86_64.egg/newrelic/common/log_file.py", line 79, in initialize_logging
    _initialize_file_logging(log_file, log_level)
  File "/srv/python27-apps/pleiades4/eggs/newrelic-2.62.0.47-py2.7-linux-x86_64.egg/newrelic/common/log_file.py", line 51, in _initialize_file_logging
    handler = logging.FileHandler(log_file)
  File "/usr/local/python/2.7.11/lib/python2.7/logging/__init__.py", line 905, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/python/2.7.11/lib/python2.7/logging/__init__.py", line 935, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/tmp/newrelic-python-agent.log'
2016-08-09 16:54:33,125 (5989/MainThread) newrelic.config INFO - Deprecated setting found: ignored_params. Please use new setting: attributes.exclude. For the new setting, an ignored parameter should be prefaced with "request.parameters.". For example, ignoring a parameter named "foo" should be added added to attributes.exclude as "request.parameters.foo."
2016-08-09 16:54:33,126 (5989/MainThread) newrelic.config INFO - Deprecated setting found: capture_params. Please use new setting: attributes.exclude. To disable capturing all request parameters, add "request.parameters.*" to attributes.exclude.
/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/patches/security.py:41: UserWarning: The set_schema option of the <require /> directive is not supported in Zope 2. Ignored for <class 'pleiades.workspace.content.workspace.Workspace'>
  return old_require(self, *args, **kw)
/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/patches/security.py:41: UserWarning: The set_schema option of the <require /> directive is not supported in Zope 2. Ignored for <class 'pleiades.workspace.content.workspace.WorkspaceCollection'>
  return old_require(self, *args, **kw)
/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/patches/security.py:41: UserWarning: The set_schema option of the <require /> directive is not supported in Zope 2. Ignored for <class 'pleiades.workspace.content.folder.WorkspaceFolder'>
  return old_require(self, *args, **kw)
2016-08-09 16:54:36 WARNING Init Class pleiades.atom.metadata.AtomAnnotatableAdapter has a security declaration for nonexistent method 'categories'
2016-08-09 16:54:36 WARNING Init Class Products.Five.metaclass.RedirectsView has a security declaration for nonexistent method 'errors'
2016-08-09 16:54:37 WARNING OFS.Uninstalled Could not import class 'CallProfiler' from module 'Products.CallProfiler.CallProfiler'
2016-08-09 16:54:37 WARNING OFS.Uninstalled Could not import class 'ZopeProfiler' from module 'Products.ZopeProfiler.ZopeProfiler'
2016-08-09 16:54:37 WARNING PlacelessTranslationService Disabled by environment variable "DISABLE_PTS". 


Starting batch content update...

Updating object at path: places/70978
Found Place with title "Untitled"
Workflow state: published.
2016-08-09 16:54:37 WARNING OFS.Uninstalled Could not import class 'IRatingCategoryAssignment' from module 'plone.contentratings.interfaces'
Checked out working copy.
Set "title" to: "Unnamed roads in the area of Vorgium". Old value: "Untitled"
2016-08-09 16:54:41 WARNING pleiades.vaytrou Failed to unindex_doc -1127213101: {'status': '500', 'content-length': '93', 'content-type': 'text/html; charset=UTF-8', 'server': 'TornadoServer/1.1'}
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:41 ERROR Zope.UnIndex KeywordIndex: unindex_object could not remove documentId -1127213101 from index object_provides.  This should not happen.
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 157, in removeForwardIndexEntry
    indexRow.remove(documentId)
KeyError: -1127213101
2016-08-09 16:54:42 WARNING pleiades.vaytrou Failed to unindex_doc 1604313964: {'status': '500', 'content-length': '93', 'content-type': 'text/html; charset=UTF-8', 'server': 'TornadoServer/1.1'}
Checked in working copy.
Updated "Unnamed roads in the area of Vorgium".

Updated content in Plone.
```

I do note that there have been entries made in the history, consistent with checkout and checkin of a working copy, but (1) `--workflow=draft` should have prevented checkin, and (2) no change is evident in the title.

<img width="927" alt="screen shot 2016-08-09 at 4 04 28 pm" src="https://cloud.githubusercontent.com/assets/263285/17533601/223d2b3e-5e4b-11e6-9b98-87127c46848e.png">

**Comment by cguardia** [comment]
@paregorios seems like I misunderstood the intent of the workflow option. From the description here, I believe this is what should happen:
- if workflow is 'draft': check out the content, make changes, do not check in.
- if workflow is 'review': check out the content, make changes, submit for review, do not check in.
- if workflow is 'publish': check out the content, make changes, submit for review, auto publish, check in.

Is this correct?

Not sure what the unindexing error is about, will check that.

**Comment by cguardia** [comment]
@paregorios also, the correct user to run the scripts is plone_daemon, sorry about the confusion.

**Comment by paregorios** [comment]
@cguardia your description above matches what I expect regarding workflow, but it doesn't seem to be what is happening. I will try running my test again with the correct user and will report back.

**Comment by paregorios** [comment]
Here's the run this morning. All but one of the unindex errors is gone, but note:
-  the "Checked in working copy" notice in the log despite `--workflow=draft`
- although its history shows the baseline creation and batch edit, the title of http://pleiades.jazkarta.com/places/70978 does not seem to have changed

```
$ cd /srv/python27-apps/pleiades4
$ sudo su plone_daemon
$ bin/instance1 run scripts/batch_update.py --workflow=draft /home/thomase/updates-test.json
2016-08-10 05:32:38 WARNING Init Class Products.LDAPUserFolder.LDAPUserFolder.LDAPUserFolder has a security declaration for nonexistent method 'getEncryptedPassword'
2016-08-10 05:32:38 WARNING Init Class Products.LDAPUserFolder.LDAPUserFolder.LDAPUserFolder has a security declaration for nonexistent method 'getEncryptedPassword'
2016-08-10 05:32:39 WARNING SecurityInfo Conflicting security declarations for "getPlaceTypeRaw"
2016-08-10 05:32:39 WARNING SecurityInfo Class "Place" had conflicting security declarations
2016-08-10 05:32:39 WARNING ZODB.blob (13597) Blob dir /srv/python27-apps/pleiades4/var/blobstorage/ has insecure mode setting
/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/patches/security.py:41: UserWarning: The set_schema option of the <require /> directive is not supported in Zope 2. Ignored for <class 'pleiades.workspace.content.workspace.Workspace'>
  return old_require(self, *args, **kw)
/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/patches/security.py:41: UserWarning: The set_schema option of the <require /> directive is not supported in Zope 2. Ignored for <class 'pleiades.workspace.content.workspace.WorkspaceCollection'>
  return old_require(self, *args, **kw)
/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/patches/security.py:41: UserWarning: The set_schema option of the <require /> directive is not supported in Zope 2. Ignored for <class 'pleiades.workspace.content.folder.WorkspaceFolder'>
  return old_require(self, *args, **kw)
2016-08-10 05:32:44 WARNING Init Class pleiades.atom.metadata.AtomAnnotatableAdapter has a security declaration for nonexistent method 'categories'
2016-08-10 05:32:45 WARNING Init Class Products.Five.metaclass.RedirectsView has a security declaration for nonexistent method 'errors'
2016-08-10 05:32:45 WARNING OFS.Uninstalled Could not import class 'CallProfiler' from module 'Products.CallProfiler.CallProfiler'
2016-08-10 05:32:45 WARNING OFS.Uninstalled Could not import class 'ZopeProfiler' from module 'Products.ZopeProfiler.ZopeProfiler'
2016-08-10 05:32:45 WARNING PlacelessTranslationService Disabled by environment variable "DISABLE_PTS". 


Starting batch content update...

Updating object at path: places/70978
Found Place with title "Untitled"
Workflow state: published.
2016-08-10 05:32:46 WARNING OFS.Uninstalled Could not import class 'IRatingCategoryAssignment' from module 'plone.contentratings.interfaces'
Checked out working copy.
Set "title" to: "Unnamed roads in the area of Vorgium". Old value: "Untitled"
2016-08-10 05:32:53 WARNING pleiades.vaytrou Failed to unindex_doc -1642184142: {'status': '500', 'content-length': '93', 'content-type': 'text/html; charset=UTF-8', 'server': 'TornadoServer/1.1'}
Checked in working copy.
Updated "Unnamed roads in the area of Vorgium".

Updated content in Plone.
$ 
```

**Comment by cguardia** [comment]
Yeah, I had it wrong before. It's fixed now.

**Comment by paregorios** [comment]
@cguardia new error:

```
plone_daemon@ip-172-31-29-149:/srv/python27-apps/pleiades4$ bin/instance1 run scripts/batch_update.py --workflow=draft --dry-run /home/thomase/updates-test.json 
2016-08-10 12:49:13 WARNING Init Class Products.LDAPUserFolder.LDAPUserFolder.LDAPUserFolder has a security declaration for nonexistent method 'getEncryptedPassword'
2016-08-10 12:49:13 WARNING Init Class Products.LDAPUserFolder.LDAPUserFolder.LDAPUserFolder has a security declaration for nonexistent method 'getEncryptedPassword'
2016-08-10 12:49:14 WARNING SecurityInfo Conflicting security declarations for "getPlaceTypeRaw"
2016-08-10 12:49:14 WARNING SecurityInfo Class "Place" had conflicting security declarations
2016-08-10 12:49:14 WARNING ZODB.blob (22084) Blob dir /srv/python27-apps/pleiades4/var/blobstorage/ has insecure mode setting
/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/patches/security.py:41: UserWarning: The set_schema option of the <require /> directive is not supported in Zope 2. Ignored for <class 'pleiades.workspace.content.workspace.Workspace'>
  return old_require(self, *args, **kw)
/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/patches/security.py:41: UserWarning: The set_schema option of the <require /> directive is not supported in Zope 2. Ignored for <class 'pleiades.workspace.content.workspace.WorkspaceCollection'>
  return old_require(self, *args, **kw)
/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/patches/security.py:41: UserWarning: The set_schema option of the <require /> directive is not supported in Zope 2. Ignored for <class 'pleiades.workspace.content.folder.WorkspaceFolder'>
  return old_require(self, *args, **kw)
2016-08-10 12:49:17 WARNING Init Class pleiades.atom.metadata.AtomAnnotatableAdapter has a security declaration for nonexistent method 'categories'
2016-08-10 12:49:18 WARNING Init Class Products.Five.metaclass.RedirectsView has a security declaration for nonexistent method 'errors'
2016-08-10 12:49:18 WARNING OFS.Uninstalled Could not import class 'CallProfiler' from module 'Products.CallProfiler.CallProfiler'
2016-08-10 12:49:18 WARNING OFS.Uninstalled Could not import class 'ZopeProfiler' from module 'Products.ZopeProfiler.ZopeProfiler'
2016-08-10 12:49:18 WARNING PlacelessTranslationService Disabled by environment variable "DISABLE_PTS". 


Starting batch content update...

Updating object at path: places/70978
Found Place with title "Untitled"
Workflow state: published.
2016-08-10 12:49:19 WARNING OFS.Uninstalled Could not import class 'IRatingCategoryAssignment' from module 'plone.contentratings.interfaces'
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/parts/instance1/bin/interpreter", line 314, in <module>
    exec _val
  File "<string>", line 1, in <module>
  File "scripts/batch_update.py", line 111, in <module>
    working_copy = policy.checkout(container)
  File "/srv/python27-apps/pleiades4/eggs/plone.app.iterate-2.1.13-py2.7.egg/plone/app/iterate/policy.py", line 65, in checkout
    working_copy, relation = copier.copyTo( container )
  File "/srv/python27-apps/pleiades4/src/pleiades.iterate/pleiades/iterate/copier.py", line 51, in copyTo
    wc = self._copyBaseline(container)
  File "/srv/python27-apps/pleiades4/src/pleiades.iterate/pleiades/iterate/copier.py", line 202, in _copyBaseline
    result = container.manage_pasteObjects(clipboard)
  File "/srv/python27-apps/pleiades4/eggs/Zope2-2.13.23-py2.7.egg/OFS/CopySupport.py", line 235, in manage_pasteObjects
    self._setObject(id, ob)
  File "/srv/python27-apps/pleiades4/eggs/Products.BTreeFolder2-2.13.3-py2.7.egg/Products/BTreeFolder2/BTreeFolder2.py", line 455, in _setObject
    notify(ObjectAddedEvent(ob, self, id))
  File "/srv/python27-apps/pleiades4/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/srv/python27-apps/pleiades4/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/srv/python27-apps/pleiades4/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/srv/python27-apps/pleiades4/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/srv/python27-apps/pleiades4/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/srv/python27-apps/pleiades4/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
    zope.component.subscribers((event.object, event), None)
  File "/srv/python27-apps/pleiades4/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/srv/python27-apps/pleiades4/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/srv/python27-apps/pleiades4/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/srv/python27-apps/pleiades4/eggs/Products.CMFCore-2.2.9-py2.7.egg/Products/CMFCore/CMFCatalogAware.py", line 263, in handleContentishEvent
    ob.indexObject()
  File "/srv/python27-apps/pleiades4/eggs/Products.Archetypes-1.9.10-py2.7.egg/Products/Archetypes/CatalogMultiplex.py", line 39, in indexObject
    c.catalog_object(self, url)
  File "/srv/python27-apps/pleiades4/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/CatalogTool.py", line 353, in catalog_object
    update_metadata, pghandler=pghandler)
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/ZCatalog.py", line 476, in catalog_object
    update_metadata=update_metadata)
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/Catalog.py", line 360, in catalogObject
    blah = x.index_object(index, object, threshold)
  File "/srv/python27-apps/pleiades4/eggs/Products.ZCTextIndex-2.13.5-py2.7-linux-x86_64.egg/Products/ZCTextIndex/ZCTextIndex.py", line 184, in index_object
    text = text()
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/content/Work.py", line 116, in Cites
    return self.rangesText()
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/content/Work.py", line 112, in rangesText
    return  "; ".join([c['range'] for c in self.getReferenceCitations()])
KeyError: 'range'
```

**Comment by cguardia** [comment]
@paregorios the citations for this place (/plone/places/copy_of_70978) do not have a 'range' key, which is required by the PleaidesEntity code.

Is this normal? Does the current value look ok?

[{'bibliographic_uri': 'http://openlibrary.org/works/OL8327792W', 'alternate_uri': '', 'formatted_citation': 'BAtlas 7', 'short_title': '', 'identifier': ' ', 'type': 'seeFurther', 'citation_detail': '', 'access_uri': ''}, {'bibliographic_uri': 'http://atlantides.org/bibliography/p.html#Pape-1978', 'alternate_uri': '', 'formatted_citation': 'Pape 1978, 52-62', 'short_title': '', 'identifier': ' ', 'type': 'seeFurther', 'citation_detail': '', 'access_uri': ''}, {'bibliographic_uri': 'http://atlantides.org/bibliography/c.html#CAG-29', 'alternate_uri': '', 'formatted_citation': 'CAG 29, 28-29', 'short_title': '', 'identifier': ' ', 'type': 'seeFurther', 'citation_detail': '', 'access_uri': ''}]

**Comment by paregorios** [comment]
@cguardia can you ask @alecpm to look at [this](https://github.com/isawnyu/pleiades-gazetteer/issues/200#issuecomment-239041679)? My suspicion is that, since the problem is with the references, it might have to do with the new bibliographic code that he has running on staging right now ([Scrumdo Story #60](https://www.scrumdo.com/projects/project/pleiades/iteration/133820#story_1096457)).

FWIW, the question about the range key is deeper into the code than my knowledge extends.

cc @skleinfeldt

**Comment by alecpm** [comment]
This one is on me. Fixing now.

**Comment by cguardia** [comment]
@alecpm thanks a lot. I was a bit confused that this hadn't come up in any of my tests.

**Comment by alecpm** [comment]
Should be fixed on staging now.

**Comment by cguardia** [comment]
Now getting a KeyError on 'title' in the same rangesText method:

  File "/srv/python27-apps/pleiades4/eggs/Products.ZCTextIndex-2.13.5-py2.7-linux-x86_64.egg/Products/ZCTextIndex/ZCTextIndex.py", line 184, in index_object
    text = text()
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/content/Work.py", line 117, in Cites
    return self.rangesText()
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/content/Work.py", line 113, in rangesText
    c['citation_detail'] for c in self.getReferenceCitations()])
KeyError: 'title'

**Comment by alecpm** [comment]
OK, I think it's really fixed now.

**Comment by cguardia** [comment]
It is. Thanks a lot.
