### ISSUE TITLE
batch update script fails setting plain TextField

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#319]
The batch update script, when replacing a value, tries to pass a list of values to the mutator function for TextFields like ```description```, but strings are expected.

This is a blocker for #140

```
Traceback (most recent call last):
  File "/Users/paregorios/Documents/files/P/pleiades-buildout/pleiades3-buildout/parts/instance/bin/interpreter", line 328, in <module>
    exec _val
  File "<string>", line 1, in <module>
  File "scripts/batch_update.py", line 156, in <module>
    working_copy.setDescription(value)
  File "/Users/paregorios/Documents/files/P/pleiades-buildout/pleiades3-buildout/eggs/Products.Archetypes-1.9.11-py2.7.egg/Products/Archetypes/BaseFolder.py", line 267, in setDescription
    self.getField('description').set(self, value, **kwargs)
  File "/Users/paregorios/Documents/files/P/pleiades-buildout/pleiades3-buildout/eggs/Products.Archetypes-1.9.11-py2.7.egg/Products/Archetypes/Field.py", line 1140, in set
    **kwargs)
  File "/Users/paregorios/Documents/files/P/pleiades-buildout/pleiades3-buildout/eggs/Products.Archetypes-1.9.11-py2.7.egg/Products/Archetypes/Field.py", line 1422, in _process_input
    (type(value), klass))
Products.Archetypes.exceptions.TextFieldException: Value is not File or String (<type 'list'> - <type 'list'>)
```

**Comment by paregorios** [comment]
Now in work in branch [issue319](https://github.com/isawnyu/pleiades3-buildout/tree/issue319)

**Comment by paregorios** [comment]
Fixed with https://github.com/isawnyu/pleiades3-buildout/commit/377fcfd2cc28befec2aab74ac8529aead8c0ab86
