### ISSUE TITLE
problem with JSON export dumps

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#392]
The newly enhanced JSON for Pleiades places (#345 and #367) is __almost__ working on production. Here's what __does__ work:

 - Individual JSON place URLs return the enhanced JSON (e.g., https://pleiades.stoa.org/places/579885/json)
 - Full dump of JSON is being written to ```pleiades-places.json``` and ```pleiades-errata.json``` in http://atlantides.org/downloads/pleiades/json/

Here is what is __not working__:

 - Compressed (gzipped) versions of the above files are __not__ being updated in http://atlantides.org/downloads/pleiades/json/

Assigning to both @alecpm (since there might be a buildout/ansible issue underlying this problem) and @MatthewWilkes (since he did the work on the origin tickets)

All of our distributions and updates point people to the gzipped versions, so we need this fixed as soon as practical.

**Comment by alecpm** [comment]
Testing now.

**Comment by alecpm** [comment]
So it looks like the dump process is failing silently any and causing the script to exit before it does the file renaming and gzipping. The dump files appear to be incomplete (lacking a final closing `}` and probably some number of objects). The log has an indication of the error source:

```Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/parts/debug-instance/bin/interpreter", line 331, in <module>
    exec _val
  File "<string>", line 1, in <module>
  File "src/Products.PleiadesEntity/Products/PleiadesEntity/commands/dump.py", line 108, in <module>
    dump(app, outfolder)
  File "src/Products.PleiadesEntity/Products/PleiadesEntity/commands/dump.py", line 90, in dump
    formatter.dump_one(adapter)
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/formatters/as_json.py", line 74, in dump_one
    self.f.write(format_json(adapter))
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/formatters/as_json.py", line 37, in format_json
    ensure_ascii=False).encode('utf-8')
  File "/srv/python27-apps/pleiades4/eggs/simplejson-3.8.1-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
  File "/srv/python27-apps/pleiades4/eggs/simplejson-3.8.1-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 277, in encode
    chunks = list(chunks)
  File "/srv/python27-apps/pleiades4/eggs/simplejson-3.8.1-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 655, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/srv/python27-apps/pleiades4/eggs/simplejson-3.8.1-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 614, in _iterencode_dict
    for chunk in chunks:
  File "/srv/python27-apps/pleiades4/eggs/simplejson-3.8.1-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 483, in _iterencode_list
    chunks = _iterencode(for_json(), _current_indent_level)
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/adapters/__init__.py", line 65, in for_json
    return collect_export_data(self)
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/adapters/__init__.py", line 31, in collect_export_data
    value = getter()
  File "/srv/python27-apps/pleiades4/eggs/plone.memoize-1.1.2-py2.7.egg/plone/memoize/instance.py", line 51, in memogetter
    val = func(*args, **kwargs)
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/adapters/connection.py", line 28, in connectsTo
    return adapter.uri()
AttributeError: 'NoneType' object has no attribute 'uri'```

**Comment by alecpm** [comment]
Looking at the code it seems like that could only happen if it found a connection with an empty place (or with the place filled with some non-adaptable object). Looks like the error likely occurred on `/places/462204` `Euryelos` which throws an error for non-authenticated users:

```User Name
Anonymous User (None)
Request URL
https://pleiades.stoa.org/places/462204/base_view
Exception Type
WorkflowException
Exception Value
No workflow provides '${name}' information.
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.CMFCore.FSPageTemplate, line 237, in _exec
Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
Module Products.PageTemplates.PageTemplate, line 87, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Warning: Macro expansion failed
Warning: <type 'exceptions.KeyError'>: 'macro'
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
Module newrelic.api.function_trace, line 110, in literal_wrapper
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 852, in do_condition
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 531, in do_optTag_tal
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
Module zope.tales.tales, line 696, in evaluate
URL: file:/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt
Line 185, Column 12
Expression: <PathExpr standard:u'context/@@connections-listing|nothing'>
Names:
{'container': <Place at /plone/places/462204>, 'context': <Place at /plone/places/462204>, 'default': <object object at 0x7f776a29a520>, 'here': <Place at /plone/places/462204>, 'loop': {}, 'nothing': None, 'options': {'args': ()}, 'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f772a7f73c0>, 'request': <HTTPRequest, URL=https://pleiades.stoa.org/places/462204/base_view>, 'root': <Application at >, 'template': <FSPageTemplate at /plone/places/462204/base_view>, 'traverse_subpath': [], 'user': <SpecialUser 'Anonymous User'>}
Module zope.tales.expressions, line 217, in __call__
Module Products.PageTemplates.Expressions, line 155, in _eval
Module Products.PageTemplates.Expressions, line 117, in render
Module Products.PleiadesEntity.browser.attestations, line 127, in __call__
Module Products.PleiadesEntity.browser.attestations, line 467, in rows
Module Products.CMFCore.WorkflowTool, line 263, in getInfoFor
WorkflowException: No workflow provides '${name}' information.```

**Comment by alecpm** [comment]
This is just one of those `Zombie` connections (#337) breaking the export isn't it?

**Comment by alecpm** [comment]
Seeing an interesting warning in the output on staging:

`Inaccessible published object /plone/Members/jatkins/anglo-saxon-burial-mounds/4
23593605`
`Inaccessible published object /plone/Members/rmoffat/kato-lefkos/324843879`

These appear to be published objects that live inside of private member folders.

**Comment by alecpm** [comment]
OK, the script appears to be running cleanly now. During the run it detected a few connection objects that don't have catalog records. These can be manually fixed by editing and saving them, I believe:

```
2019-04-15 20:02:48 WARNING PleiadesEntity.adapters.connection Could not find catalog brain for /plone/places/423031/423080
2019-04-15 20:02:48 WARNING PleiadesEntity.adapters.connection Could not find catalog brain for /plone/places/423031/422995
2019-04-15 20:02:51 WARNING PleiadesEntity.adapters.connection Could not find catalog brain for /plone/places/423080/1356
2019-04-15 20:02:51 WARNING PleiadesEntity.adapters.connection Could not find catalog brain for /plone/places/423080/423031
```

Additionally, the original error was due to connection objects whose target could not be found by the script. There were only two of these:

```
2019-04-15 20:02:48 WARNING PleiadesEntity.adapters.connection No connection target found for connection /plone/places/423038/423025
2019-04-15 19:48:33 WARNING PleiadesEntity.adapters.connection No connection target found for connection /plone/places/462204/462503
```

**Comment by paregorios** [comment]
I have checked the four connections reported as having no catalog entry. Here's the status:

 - Staging: cannot address because blocked by #394 
 - Production: these also had no catalog records on production (I used the ZMI to check). I manually edited each of them through the Plone then check the ZMI again. They all have catalog entries now.

**Comment by paregorios** [comment]
I have checked the two connections reported as having a target that could not be found by the script. Here's the status:

 - Staging: cannot address because blocked by #394 
 - Production: cannot reproduce problem through the Plone. Here is what I find:
    - Connection [423038/423025](https://pleiades.stoa.org/places/423038/423025) has target [Roma](https://pleiades.stoa.org/places/423025), which exists  
    - Connection [462204/462503](https://pleiades.stoa.org/places/462204/462503) has target [Syracusae/Syrakousai](https://pleiades.stoa.org/places/462503), which exists

**Comment by alecpm** [comment]
That last script output was from production. I'm curious if the 423038/423025 and 462204/462503 connections appear in the dump, given that they triggered that warning.

**Comment by paregorios** [comment]
Something's weird regarding 423038/423025 and 462204/462503. Trying to de-reference the ```/json``` URI from the parent place through the webapp throws an error. E.g., https://pleiades.stoa.org/places/423038/json yieds:

```
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.PleiadesEntity.browser.formatters.as_json, line 98, in __call__
    Module Products.PleiadesEntity.browser.formatters.as_json, line 37, in format_json
    Module simplejson, line 397, in dumps
    Module simplejson.encoder, line 277, in encode
    Module simplejson.encoder, line 655, in _iterencode
    Module simplejson.encoder, line 614, in _iterencode_dict
    Module simplejson.encoder, line 483, in _iterencode_list
    Module Products.PleiadesEntity.browser.adapters, line 65, in for_json
    Module Products.PleiadesEntity.browser.adapters, line 31, in collect_export_data
    Module plone.memoize.instance, line 51, in memogetter
    Module Products.PleiadesEntity.browser.adapters.connection, line 28, in connectsTo

AttributeError: 'NoneType' object has no attribute 'uri' 
```

Ditto for https://pleiades.stoa.org/places/462204/json

**Comment by paregorios** [comment]
ahah:

![Screen Shot 2019-04-16 at 1 12 37 PM](https://user-images.githubusercontent.com/263285/56233720-56ffe200-6049-11e9-88fb-01737f4e0207.png)

**Comment by paregorios** [comment]
But:

![Screen Shot 2019-04-16 at 1 15 12 PM](https://user-images.githubusercontent.com/263285/56233902-b5c55b80-6049-11e9-845f-248daecf3067.png)

**Comment by paregorios** [comment]
Are these zombie connections?

**Comment by MatthewWilkes** [comment]
They do indeed look like the Zombie connections.

**Comment by paregorios** [comment]
All updates are occurring as expected on production. Closing as resolved (noting that the separate "zombie connections" ticket #337 is still not resolved).
