### ISSUE TITLE
Zotero imports are failing

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#453]
Steps to reproduce:

- Log in
- Create a new content item that supports "references" (place, name, location, connection) or edit an existing one.
- Navigate to "references" tab, add a new reference, paste a valid zotero URI (like https://www.zotero.org/groups/2533/items/MDVTXNTU) into the "bibliographic URI field, and click the "Fetch Zotero" button.
- A pop-up appears like this:

![Screen Shot 2021-10-04 at 9 06 17 AM](https://user-images.githubusercontent.com/263285/135866342-53ef4017-bfad-4ea8-bdc1-54499aa5ec37.png)

**Comment by paregorios** [comment]
```bash
$ grep -A 20 -i '2021-10-04.*zotero' instance?.log
instance3.log:2021-10-04T10:06:05 INFO requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): www.zotero.org
instance3.log-------
instance3.log:2021-10-04T10:06:05 ERROR isaw.bibitems Error fetching Zotero web page: https://www.zotero.org/groups/2533/items/MDVTXNTU
instance3.log-Traceback (most recent call last):
instance3.log-  File "/srv/python27-apps/pleiades4/src/isaw.bibitems/src/isaw/bibitems/zotero.py", line 31, in fetch
instance3.log-    response = requests.get(uri, headers=self.request_headers)
instance3.log-  File "/srv/python27-apps/pleiades4/eggs/requests-2.10.0-py2.7.egg/requests/api.py", line 71, in get
instance3.log-    return request('get', url, params=params, **kwargs)
instance3.log-  File "/srv/python27-apps/pleiades4/eggs/newrelic-2.100.0.84-py2.7-linux-aarch64.egg/newrelic/api/external_trace.py", line 58, in dynamic_wrapper
instance3.log-    return wrapped(*args, **kwargs)
instance3.log-  File "/srv/python27-apps/pleiades4/eggs/requests-2.10.0-py2.7.egg/requests/api.py", line 57, in request
instance3.log-    return session.request(method=method, url=url, **kwargs)
instance3.log-  File "/srv/python27-apps/pleiades4/eggs/requests-2.10.0-py2.7.egg/requests/sessions.py", line 475, in request
instance3.log-    resp = self.send(prep, **send_kwargs)
instance3.log-  File "/srv/python27-apps/pleiades4/eggs/newrelic-2.100.0.84-py2.7-linux-aarch64.egg/newrelic/api/external_trace.py", line 58, in dynamic_wrapper
instance3.log-    return wrapped(*args, **kwargs)
instance3.log-  File "/srv/python27-apps/pleiades4/eggs/requests-2.10.0-py2.7.egg/requests/sessions.py", line 585, in send
instance3.log-    r = adapter.send(request, **kwargs)
instance3.log-  File "/srv/python27-apps/pleiades4/eggs/requests-2.10.0-py2.7.egg/requests/adapters.py", line 477, in send
instance3.log-    raise SSLError(e, request=request)
instance3.log-SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```

**Comment by alecpm** [comment]
Should be working now. I installed an updated certifi package in the virtualenv. I still need to update the ansible scripts.

**Comment by paregorios** [comment]
Confirmed working. Thanks @alecpm! Shall we leave this ticket open (priority downgraded) until the ansible scripts are updated?

**Comment by alecpm** [comment]
Sounds good.

**Comment by alecpm** [comment]
I think this should be done now. The buildout is updated and running correctly. I've also updated to the latest 2021 certifi in the version pins.
