### ISSUE TITLE
place_maker script doesn't handle multiple IDs for locations

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#457]
When there's more than one location in a place: 

```
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/parts/instance1/bin/interpreter", line 332, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "scripts/place_maker.py", line 189, in <module>
    populate_locations(place, content, args)
  File "scripts/place_maker.py", line 63, in populate_locations
    geometry=json.dumps(location['geometry'])
  File "/srv/python27-apps/pleiades4/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/srv/python27-apps/pleiades4/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/TypesTool.py", line 833, in constructContent
    ob = info.constructInstance(container, id, *args, **kw)
  File "/srv/python27-apps/pleiades4/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/TypesTool.py", line 311, in constructInstance
    return self._constructInstance(container, id, *args, **kw)
  File "/srv/python27-apps/pleiades4/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/TypesTool.py", line 552, in _constructInstance
    newid = m(id, *args, **kw)
  File "<string>", line 4, in addLocation
  File "/srv/python27-apps/pleiades4/eggs/Zope2-2.13.30-py2.7.egg/OFS/ObjectManager.py", line 325, in _setObject
    v = self._checkId(id)
  File "/srv/python27-apps/pleiades4/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/PortalFolder.py", line 310, in _checkId
    PortalFolderBase.inheritedAttribute('_checkId')(self, id, allow_dup)
  File "/srv/python27-apps/pleiades4/eggs/Zope2-2.13.30-py2.7.egg/OFS/ObjectManager.py", line 116, in checkValidId
    'The id "%s" is invalid - it is already in use.' % id)
zExceptions.BadRequest: The id "plan-location-of-e-street" is invalid - it is already in use.
```

Ideal solution:
- Read location ID from input JSON file if present
- If not present in input file: generate and add numeric one-up final component if more than one item in list

This is blocking next step on Dura Europos imports

**Comment by paregorios** [comment]
This is resolved with https://github.com/isawnyu/pleiades3-buildout/pull/7
