### ISSUE TITLE
connection handling in place_maker script

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#458]
The placemaker script currently (and evidently successfully) caches IDs for places it creates during a given run so that it can make a second pass to create connections specified in the same run to those places; however, it does not handle properly a connection specification in the input that identifies a pre-existing place resource by place ID or by Pleiades place URI. It should do so. In fact, it throws a key error like:

```bash
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/parts/instance1/bin/interpreter", line 332, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "scripts/place_maker.py", line 241, in <module>
    to_id = FALLBACK_IDS[connection['connection']]
KeyError: u'https://pleiades.stoa.org/places/15685985'
```

because there is some crufty, once-upon-a-time code that is trying to handle a specific connection case in Dura-Europos data that should not be part of the place_maker script at all.

**Comment by paregorios** [comment]
Now in work in branch `issue458`.
