### ISSUE TITLE
Nightly exports failing

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#523]
Nightly exports have failed yesterday and today.

**Comment by paregorios** [comment]
In `dump.log` we see:

```
2024-10-31 06:29:52 ERROR Products.PleiadesEntity.browser.adapters.location Access to the referenced accuracy object "https://pleiades.stoa.org/features/metadata/841fd46a-797f-4a7f-982c-5257df8f6129" is not authorized. Context: "https://pleiades.stoa.org/places/705163202/imagery-location-ponte-caldaro". None
2024-10-31 06:34:46 WARNING Products.PleiadesEntity.browser.adapters Could not find catalog brain for /plone/places/334776904/castel-santangelo
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/parts/debug-instance/bin/interpreter", line 338, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "src/Products.PleiadesEntity/Products/PleiadesEntity/commands/dump.py", line 113, in <module>
    dump(app, outfolder)
  File "src/Products.PleiadesEntity/Products/PleiadesEntity/commands/dump.py", line 95, in dump
    formatter.dump_one(adapter)
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/formatters/as_csv.py", line 138, in dump_one
    for name in adapter.names()]
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/formatters/as_csv.py", line 101, in format_csv
    value = column.get(adapter)
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/formatters/as_csv.py", line 17, in get
    getter = getattr(adapter, self.sourceName)
AttributeError: 'NoneType' object has no attribute 'author_names'
```

**Comment by paregorios** [comment]
- I have published the draft PAA that caused the first ERROR for https://pleiades.stoa.org/places/705163202/imagery-location-ponte-caldaro
- I have used the ZMI to reindex the portal_catalog for everything in `/plone/places/334776904` (the name in question was deleted through the plone two days ago; evidently a reindex was not triggered and the brain for the place is still holding a reference to the deleted name?)
- I am now manually re-running the dump-all script

**Comment by paregorios** [comment]
Despite reindexing, the final error is still occurring:

```
2024-10-31 09:36:27 WARNING Products.PleiadesEntity.browser.adapters Could not find catalog brain for /plone/places/334776904/castel-santangelo
Traceback (most recent call last):
  File "/srv/python27-apps/pleiades4/parts/debug-instance/bin/interpreter", line 338, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "src/Products.PleiadesEntity/Products/PleiadesEntity/commands/dump.py", line 113, in <module>
    dump(app, outfolder)
  File "src/Products.PleiadesEntity/Products/PleiadesEntity/commands/dump.py", line 95, in dump
    formatter.dump_one(adapter)
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/formatters/as_csv.py", line 138, in dump_one
    for name in adapter.names()]
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/formatters/as_csv.py", line 101, in format_csv
    value = column.get(adapter)
  File "/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/browser/formatters/as_csv.py", line 17, in get
    getter = getattr(adapter, self.sourceName)
AttributeError: 'NoneType' object has no attribute 'author_names'
```

**Comment by paregorios** [comment]
We appear to have a working copy that is somehow masquerading as the baseline of this name and the baseline is gone (deleted)?

**Comment by paregorios** [comment]
I have deleted via the ZMI `copy_of_castel-santangelo` and am now manually rerunning the dump script.

**Comment by paregorios** [comment]
Export ran to completion, but now there is a "null" connection in the JSON serialization of the same place object:

```
    "connections": [
        null,
        {
            "@type": "Connection",
            "associationCertainty": "certain",
            "attestations": [],
            "connectionType": "part_of_analytical",
            "connectionTypeURI": "https://pleiades.stoa.org/vocabularies/relationship-types/part_of_analytical",
            "connectsTo": "https://pleiades.stoa.org/places/217953464",
            "contributors": [],
            "created": "2024-10-25T14:02:43Z",
            "creators": [
                {
                    "homepage": null,
```

**Comment by paregorios** [comment]
Have cleaned out and reindexed the offending place and its subordinate components. Rerunning the export.

**Comment by paregorios** [comment]
Worked.
